export const ARENA_WIDTH = 960;
export const ARENA_HEIGHT = 540;
export const ARENA_WALL_THICKNESS = 24;

export const NORTHWEST_PILLAR_X = 390;
export const NORTHWEST_PILLAR_Y = 80;
export const NORTHWEST_PILLAR_WIDTH = 72;
export const NORTHWEST_PILLAR_HEIGHT = 150;
export const SOUTHEAST_PILLAR_X = 510;
export const SOUTHEAST_PILLAR_Y = 310;
export const SOUTHEAST_PILLAR_WIDTH = 72;
export const SOUTHEAST_PILLAR_HEIGHT = 150;

export const PLAYER_MOVE_SPEED = 240;
export const PLAYER_RADIUS = 18;
export const PLAYER_MAX_HP = 100;
export const PLAYER_MAX_MP = 100;
export const PLAYER_INVULNERABILITY_FRAMES = 30;
export const PLAYER_HIT_KNOCKBACK_RADIUS = 150;
export const PLAYER_HIT_KNOCKBACK_DISTANCE = 72;
export const PLAYER_HIT_KNOCKBACK_FRAMES = 6;
export const PLAYER_DAMAGE_SHAKE_DURATION_MS = 100;
export const PLAYER_DAMAGE_SHAKE_INTENSITY = 0.004;

export const SWORDSMAN_RADIUS = 22;
export const SWORDSMAN_MAX_HP = 100;
export const SWORDSMAN_MOVE_SPEED = 110;
export const SWORDSMAN_ATTACK_TRIGGER_DISTANCE = 80;
export const SWORDSMAN_ATTACK_REACH = 84;
export const SWORDSMAN_ATTACK_RADIUS = 10;
export const SWORDSMAN_ATTACK_DAMAGE = 20;
export const SWORDSMAN_WINDUP_FRAMES = 30;
export const SWORDSMAN_ACTIVE_FRAMES = 6;
export const SWORDSMAN_RECOVERY_FRAMES = 36;
export const SWORDSMAN_RESPAWN_FRAMES = 90;

export const ARCHER_RADIUS = 20;
export const ARCHER_MAX_HP = 80;
export const ARCHER_MOVE_SPEED = 90;
export const ARCHER_MIN_DISTANCE = 260;
export const ARCHER_MAX_DISTANCE = 380;
export const ARCHER_WINDUP_FRAMES = 42;
export const ARCHER_RECOVERY_FRAMES = 72;
export const ARCHER_ATTACK_DAMAGE = 15;
export const ARCHER_RESPAWN_FRAMES = 120;

export const FORMATION_SWORDSMAN_HOLD_X = 614;
export const FORMATION_SWORDSMAN_HOLD_Y = 324;
export const FORMATION_ARCHER_HOLD_X = 787;
export const FORMATION_ARCHER_HOLD_Y = 250;
export const FORMATION_SWORDSMAN_PRESS_X = 490;
export const FORMATION_SWORDSMAN_PRESS_Y = 270;
export const FORMATION_ARCHER_PRESS_X = 690;
export const FORMATION_ARCHER_PRESS_Y = 250;
export const FORMATION_PRESS_TRIGGER_X = 390;
export const FORMATION_BREAK_TRIGGER_X = 610;
export const FORMATION_GUARD_RADIUS = 170;

export const SLOW_WORLD_TIME_SCALE = 0.25;
export const SLOW_MP_DRAIN_PER_SECOND = 25;
export const MP_RECOVERY_PER_SECOND = 15;

export const TELEPORT_MAX_DISTANCE = 240;
export const TELEPORT_COOLDOWN_FRAMES = 90;

export const LONGSWORD_REACH = 180;
export const LONGSWORD_BLADE_RADIUS = 8;
export const LONGSWORD_SWING_RADIANS = (Math.PI * 4) / 9;
export const LONGSWORD_ACTIVE_FRAMES = 9;
export const LONGSWORD_COOLDOWN_FRAMES = 18;
export const LONGSWORD_DAMAGE = 35;

export const BOW_PROJECTILE_SPEED = 720;
export const BOW_PROJECTILE_RADIUS = 5;
export const BOW_PROJECTILE_LIFETIME_FRAMES = 90;
export const BOW_COOLDOWN_FRAMES = 18;
export const BOW_DAMAGE = 20;

export const MAGIC_PROJECTILE_SPEED = 240;
export const MAGIC_PROJECTILE_RADIUS = 8;
export const MAGIC_PROJECTILE_LIFETIME_FRAMES = 240;
export const MAGIC_TURN_SPEED_RADIANS_PER_SECOND = 12;
export const MAGIC_COOLDOWN_FRAMES = 30;
export const MAGIC_DAMAGE = 30;

export const HIT_STOP_FRAMES = 4;
export const HIT_FLASH_FRAMES = 6;
